# Site
repository: jojoldu/jojoldu.github.io
# favicon: images/favicon.ico

# Personal info
name: TYLER AN  
title: FrontEnd Developer
email: jum94kr@gmail.com
website: jum94kr.github.io
Phone: 0414 457 230

# Social links
github_username:  jum94kr
linkedin_username: hongchangan

# About Section
# about_title: About Me
about_profile_image: images/myprofile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi I'm a FrontEnd Developer with a passion for creating beautiful and engaging web experiences. With over a year of experience in web development, I have a strong background in <mark>HTML</mark>, <mark>CSS</mark>, and <mark>JavaScript</mark> and have experience using popular front-end frameworks such as <mark>React</mark>. I'm well-versed in modern web development practices and I'm always looking to improve my skills. I'm particularly interested in back-end development and I'm eager to expand my skillset. I'm a quick learner and always eager to take on new challenges. I would love to connect with you and share more about my experience and how I can contribute to your team. Let's make something great together!


# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience




  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
