# Site
repository: https://github.com/jum94kr/jum94kr.github.io
# favicon: images/favicon.ico

# Personal info
name: TYLER AN  
title: Network Engineer / FrontEnd Developer
email: jum94kr@gmail.com
website: jum94kr.github.io
Phone: +82 10 5801 5164

# Social links
github_username:  jum94kr
linkedin_username: hongchangan

# About Section
# about_title: About Me
about_profile_image: images/myprofile.jpg
about_content: | # this will include new lines to allow paragraphs
  As a detail-oriented Network Engineer, I bring 2 years of hands-on experience in designing, implementing, and maintaining high-performance network infrastructures. I have successfully configured and managed routers, switches, firewalls, and VPNs to ensure seamless connectivity across both LAN and WAN environments. My expertise includes working with Axgate and Cisco devices, with a strong focus on optimizing network performance and security.


# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience




  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
